"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, Plus, Save, Trash2 } from "lucide-react";
import { can, parseRole, type Role } from "@/lib/permissions";

type Category = { name: string; allocated: string };
export default function NewProject() {
  const router = useRouter(); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const role = typeof window === "undefined" ? "INSPECTOR" as Role : parseRole(new URLSearchParams(window.location.search).get("role") || undefined);
  const [form, setForm] = useState({ name: "", description: "", startDate: "", endDate: "", totalBudget: "", fundingOrganization: "", coInspectors: "" });
  const [categories, setCategories] = useState<Category[]>([{ name: "Equipment", allocated: "" }, { name: "Travel", allocated: "" }]);
  const change = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const changeCategory = (index: number, key: keyof Category, value: string) => setCategories((current) => current.map((category, i) => i === index ? { ...category, [key]: value } : category));
  const totalAllocated = categories.reduce((sum, category) => sum + (Number(category.allocated) || 0), 0);
  const budget = Number(form.totalBudget) || 0;
  const balanced = budget > 0 && Math.round(totalAllocated * 100) === Math.round(budget * 100);
  async function save() { setSaving(true); setError(""); if (!balanced) { setError("Category allocations must equal the total project budget."); setSaving(false); return; } const response = await fetch("/api/projects", { method: "POST", headers: { "Content-Type": "application/json", "x-demo-role": role }, body: JSON.stringify({ ...form, totalBudget: budget, categories: categories.map((category) => ({ name: category.name.trim(), allocated: Number(category.allocated) })), fundingOrganization: can(role, "addFundingOrganization") ? form.fundingOrganization : undefined }) }); const result = await response.json().catch(() => ({})); if (!response.ok) { setError(result.error || "Could not save project."); setSaving(false); return; } router.push(`/projects?created=${result.code}&role=${role}`); }
  return <main className="content"><div className="page-header"><div><button className="back-link" onClick={() => router.back()}><ArrowLeft size={15} /> Back to projects</button><h1 className="title">Create a new project</h1><div className="eyebrow">Set the locked project budget, categories, and funding structure</div></div></div>{error && <div className="notice">{error}</div>}<div className="panel"><div className="form-grid"><Field label="Project name" placeholder="e.g. AI-Based Crop Disease Detection" value={form.name} onChange={(v) => change("name", v)} full/><Field label="Project start date" type="date" value={form.startDate} onChange={(v) => change("startDate", v)}/><Field label="Project end date" type="date" value={form.endDate} onChange={(v) => change("endDate", v)}/><Field label="Total project budget" placeholder="INR 0.00" value={form.totalBudget} onChange={(v) => change("totalBudget", v)}/>{can(role, "addFundingOrganization") && <Field label="Funding organization" placeholder="Organization name" value={form.fundingOrganization} onChange={(v) => change("fundingOrganization", v)}/>}<Field label="Description" placeholder="Describe the research project" value={form.description} onChange={(v) => change("description", v)} full area/><Field label="Co-project inspector names" placeholder="Add names separated by commas" value={form.coInspectors} onChange={(v) => change("coInspectors", v)} full/></div><div className="allocation-box"><div className="section-heading"><div><h2>Category allocations</h2><span className="sub">Allocate the full budget across one or more spending categories.</span></div><span className={`pill ${balanced ? "green" : "orange"}`}><i/>{money(totalAllocated)} / {money(budget)}</span></div>{categories.map((category, index) => <div className="category-row" key={index}><input aria-label={`Category ${index + 1} name`} placeholder="Category name" value={category.name} onChange={(e) => changeCategory(index, "name", e.target.value)}/><input aria-label={`Category ${index + 1} allocation`} inputMode="decimal" placeholder="INR 0.00" value={category.allocated} onChange={(e) => changeCategory(index, "allocated", e.target.value)}/>{categories.length > 1 && <button className="icon-button" type="button" aria-label="Remove category" onClick={() => setCategories((current) => current.filter((_, i) => i !== index))}><Trash2 size={16}/></button>}</div>)}<button className="secondary" type="button" onClick={() => setCategories((current) => [...current, { name: "", allocated: "" }])}><Plus size={15}/> Add category</button></div><div className="form-actions"><button className="secondary" onClick={() => router.back()}>Cancel</button><button className="primary" onClick={save} disabled={saving || !balanced}><Save size={15} /> {saving ? "Saving..." : "Save project"}</button></div></div></main>;
}
function money(value: number) { return `INR ${value.toLocaleString("en-IN")}`; }
function Field({ label, placeholder, type = "text", value, onChange, full, area }: { label: string; placeholder?: string; type?: string; value: string; onChange: (value: string) => void; full?: boolean; area?: boolean }) { return <div className={`field ${full ? "full" : ""}`}><label>{label}</label>{area ? <textarea placeholder={placeholder} value={value} onChange={(e) => onChange(e.target.value)} /> : <input type={type} placeholder={placeholder} value={value} onChange={(e) => onChange(e.target.value)} />}</div>; }
