"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, Save } from "lucide-react";
import { can, parseRole, type Role } from "@/lib/permissions";

export default function NewProject() {
  const router = useRouter(); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const role = typeof window === "undefined" ? "INSPECTOR" as Role : parseRole(new URLSearchParams(window.location.search).get("role") || undefined);
  const [form, setForm] = useState({ name: "", description: "", startDate: "", endDate: "", totalBudget: "", fundingOrganization: "", coInspectors: "" });
  const change = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function save() { setSaving(true); setError(""); const response = await fetch("/api/projects", { method: "POST", headers: { "Content-Type": "application/json", "x-demo-role": role }, body: JSON.stringify({ ...form, totalBudget: Number(form.totalBudget), fundingOrganization: can(role, "addFundingOrganization") ? form.fundingOrganization : undefined }) }); const result = await response.json().catch(() => ({})); if (!response.ok) { setError(result.error || "Could not save project."); setSaving(false); return; } router.push(`/projects?created=${result.code}&role=${role}`); }
  return <main className="content"><div className="page-header"><div><button className="back-link" onClick={() => router.back()}><ArrowLeft size={15} /> Back to projects</button><h1 className="title">Create a new project</h1><div className="eyebrow">Set the locked project budget and funding structure</div></div></div>{error && <div className="notice">{error}</div>}<div className="panel"><div className="form-grid"><Field label="Project name" placeholder="e.g. AI-Based Crop Disease Detection" value={form.name} onChange={(v) => change("name", v)} full/><Field label="Project start date" type="date" value={form.startDate} onChange={(v) => change("startDate", v)}/><Field label="Project end date" type="date" value={form.endDate} onChange={(v) => change("endDate", v)}/><Field label="Total project budget" placeholder="INR 0.00" value={form.totalBudget} onChange={(v) => change("totalBudget", v)}/>{can(role, "addFundingOrganization") && <Field label="Funding organization" placeholder="Organization name" value={form.fundingOrganization} onChange={(v) => change("fundingOrganization", v)}/>}<Field label="Description" placeholder="Describe the research project" value={form.description} onChange={(v) => change("description", v)} full area/><Field label="Co-project inspector names" placeholder="Add names separated by commas" value={form.coInspectors} onChange={(v) => change("coInspectors", v)} full/></div><div className="form-actions"><button className="secondary" onClick={() => router.back()}>Cancel</button><button className="primary" onClick={save} disabled={saving}><Save size={15} /> {saving ? "Saving..." : "Save project"}</button></div></div></main>;
}
function Field({ label, placeholder, type = "text", value, onChange, full, area }: { label: string; placeholder?: string; type?: string; value: string; onChange: (value: string) => void; full?: boolean; area?: boolean }) { return <div className={`field ${full ? "full" : ""}`}><label>{label}</label>{area ? <textarea placeholder={placeholder} value={value} onChange={(e) => onChange(e.target.value)} /> : <input type={type} placeholder={placeholder} value={value} onChange={(e) => onChange(e.target.value)} />}</div>; }
